{-# LANGUAGE ConstraintKinds #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GADTs #-}

{-# LANGUAGE DataKinds #-}
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE RankNTypes #-}

module Raft.Types where

import Protolude

import Data.Sequence (Seq(Empty, (:<|)), (<|))
import qualified Data.Sequence as Seq
import Numeric.Natural (Natural)

type NodeId = ByteString
type NodeIds = Set NodeId

newtype Term = Term Natural
  deriving (Enum, Ord, Eq)

term0 :: Term
term0 = Term 0

incrTerm :: Term -> Term
incrTerm = succ

newtype Index = Index Natural
  deriving (Enum)

index0 :: Index
index0 = Index 0

incrIndex :: Index -> Index
incrIndex = succ

decrIndex :: Index -> Index
decrIndex = pred

data NodeConfig = NodeConfig
  { configNodeId :: NodeId
  , configNodeIds :: NodeIds
  , configElectionTimeout :: Int
  , configElectionHeartbeat :: Int
  }

-- | An entry in the replicated log
data Entry v = Entry
  { entryIndex :: Index
  , entryTerm :: Term
    -- ^ term when entry was received by leader
  , entryValue :: v
    -- ^ command to update state machine
  }

-- | The replicated log of entries on each node
newtype Log v = Log { logEntries :: Seq (Entry v) }

addLogEntry :: Log v -> Entry v -> Log v
addLogEntry (Log es) e = Log (e <| es)

lastLogEntry :: Log v -> Maybe (Index, Entry v)
lastLogEntry (Log entries) =
  case entries of
    Empty -> Nothing
    e :<| _ ->
      let logIndex = fromIntegral (Seq.length entries - 1)
       in Just (Index logIndex, e)

-- | State saved to disk before performing actions generated by event handling.
--
-- TODO This value is passed to the TransitionM monad such that the currentTerm
-- and votedFor fields can be accessed; however, the entire log is not needed.
-- Only the last log entry is needed. Soon, we should make another datatype that
-- captures this, perhaps 'PersistentStateData'.
data PersistentState v = PersistentState
  { psCurrentTerm :: Term
    -- ^ Last term server has seen
  , psVotedFor :: Maybe NodeId
    -- ^ candidate id that received vote in current term
  , psLog :: Log v
    -- ^ log entries; each entry contains command for state machine
  }

--------------------------------------------------------------------------------
-- Events
--------------------------------------------------------------------------------

data Timeout
  = ElectionTimeout
  | HearbeatTimeout

data Event v
  = Message (Message v)
  | Timeout Timeout

--------------------------------------------------------------------------------
-- Actions (TODO move to src/Raft/Action.hs)
--------------------------------------------------------------------------------

data Action v
  = SendMessage NodeId (Message v)
  | Broadcast NodeIds (Message v)
  | ResetElectionTimeout Int

--------------------------------------------------------------------------------
-- Node States
--------------------------------------------------------------------------------

data FollowerState = FollowerState
  { fsCommitIndex :: Index
    -- ^ index of highest log entry known to be committed
  , fsLastApplied :: Index
    -- ^ index of highest log entry applied to state machine
  }

data CandidateState = CandidateState
  { csCommitIndex :: Index
    -- ^ index of highest log entry known to be committed
  , csLastApplied :: Index
    -- ^ index of highest log entry applied to state machine
  , csVotes :: NodeIds
  }

data LeaderState = LeaderState
  { lsCommitIndex :: Index
    -- ^ index of highest log entry known to be committed
  , lsLastApplied :: Index
    -- ^ index of highest log entry applied to state machine
  , lsNextIndex :: Map NodeId Index
    -- ^ for each server, index of the next log entry to send to that server
  , lsMatchIndex :: Map NodeId Index
    -- ^ for each server, index of highest log entry known to be replicated on server
  }

--------------------------------------------------------------------------------
-- RPCs
--------------------------------------------------------------------------------

data Message v = RPC
  { sender :: NodeId
  , rpc :: RPC v
  }

data RPC v
  = AppendEntriesRPC (AppendEntries v)
  | AppendEntriesResponseRPC AppendEntriesResponse
  | RequestVoteRPC RequestVote
  | RequestVoteResponseRPC RequestVoteResponse

class RPCType a v where
  toRPC :: a -> RPC v

instance RPCType (AppendEntries v) v where
  toRPC = AppendEntriesRPC

instance RPCType (AppendEntriesResponse) v where
  toRPC = AppendEntriesResponseRPC

instance RPCType (RequestVote) v where
  toRPC = RequestVoteRPC

instance RPCType (RequestVoteResponse) v where
  toRPC = RequestVoteResponseRPC

data AppendEntries v = AppendEntries
  { aeTerm :: Term
    -- ^ leader's term
  , aeLeaderId :: NodeId
    -- ^ so follower can redirect clients
  , aePrevLogIndex :: Index
    -- ^ index of log entry immediately preceding new ones
  , aePrevLogTerm :: Term
    -- ^ term of aePrevLogIndex entry
  , aeEntries :: [Entry v]
    -- ^ log entries to store (empty for heartbeat)
  , aeLeaderCommit :: Index
    -- ^ leader's commit index
  }

data AppendEntriesResponse = AppendEntriesResponse
  { aerTerm :: Term
    -- ^ current term for leader to update itself
  , aerSuccess :: Bool
    -- ^ true if follower contained entry matching aePrevLogIndex and aePrevLogTerm
  }

data RequestVote = RequestVote
  { rvTerm :: Term
    -- ^ candidates term
  , rvCandidateId :: NodeId
    -- ^ candidate requesting vote
  , rvLastLogIndex :: Index
    -- ^ index of candidate's last log entry
  , rvLastLogTerm :: Term
    -- ^ term of candidate's last log entry
  }

data RequestVoteResponse = RequestVoteResponse
  { rvrTerm :: Term
    -- ^ current term for candidate to update itself
  , rvrVoteGranted :: Bool
    -- ^ true means candidate recieved vote
  }
